### ISSUE TITLE
atom-editor install fails because of package.json permissions

### ISSUE THREAD

**Issue by mbellgb** [fusion809/PKGBUILDs#1]
When running `makepkg` for atom-editor, I get the following error:
```
==> Starting build()...
Node: v5.9.0
npm: v3.8.2
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/home/mbell/git/PKGBUILDs/atom-editor/src/atom-1.6.0/package.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.Module._extensions..json (module.js:428:20)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at bootstrap (/home/mbell/git/PKGBUILDs/atom-editor/src/atom-1.6.0/script/bootstrap:90:25)
    at /home/mbell/git/PKGBUILDs/atom-editor/src/atom-1.6.0/script/bootstrap:151:3
Node: v5.9.0
npm: v3.8.2
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
```

It turns out that the permissions for `package.json` are set to 000. My workaround was to pause makepkg and manually set the permissions to 755, then continuing the script.

Pacman 5.0.1

**Comment by fusion809** [comment]
Odd, this may not be related to the PKGBUILD at all. All my PKGBUILD does, as far as the `package.json` file is concerned is remove some unnecessary and potentially privacy-violating features of Atom. I don't think that would change the permissions of this file. As a solution I will add a `chmod 755 package.json` line to the PKGBUILD.

**Comment by mbellgb** [comment]
Just tested the new version and is currently building without a problem. Thanks!
