### ISSUE TITLE
Visual-studio-code-git PKGBUID from AUR

### ISSUE THREAD

**Issue by blogericg** [fusion809/PKGBUILDs#1]
Hey all and thanks for your work.

Cannot save the changes at the top of the page, and uncomment the memory. When saving, come out from the package builder. 

Another issue:
visual-studio-code-git 1.1.0.insider.r10766.gd41c48d46-1
The Makedepend are OK with Nodejs, gulp and Git but problem with NPM ENOENT, can't perform suggested update of Minimatch

**Comment by fusion809** [comment]
Many of these packages I don't maintain any more, sorry, going to trim them so no one else gets mislead.

**Comment by blogericg** [comment]
Thanks for fast answer, sorry to hear this. 
Thinking about trying the Intel system beta visual studio version. Any suggestion?

**Comment by fusion809** [comment]
Must admit I haven't the foggiest. I hardly use any editor but Vim nowadays, so I've become out of practice for packaging VS. You could try (although beware you might find some that are impatient) emailing maintainers of VSCode package maintainers in the Arch User Repository, asking for their help.
